name: Release

on:
  push:
    branches:
      - master
      - develop
      - hotfix/**

jobs:
  build:
    name: Build, run tests and package artifacts
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.6
        ports:
          - 3306:3306
        env:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_DATABASE: mysql
          MYSQL_ROOT_PASSWORD: mysql
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@master
        with:
          versionSpec: '5.x'
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@master
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test -c Release --no-build
      - name: Package
        run: dotnet pack -c Release -o ./packages -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersion }} --no-build
      - name: Store nuget package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ./packages/*.nupkg

  deploy:
    name: Deploy to Nuget
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package from build
        uses: actions/download-artifact@v2
        with:
          name: packages
      - name: Push to Nuget
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }}